import type { Metadata } from 'next'
import { Inter, Space_Grotesk } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import AnimatedBlob from '@/components/AnimatedBlob'

const inter = Inter({ subsets: ['latin'] })
const space_grotesk = Inter({
	subsets: ['greek'],
	weight: '400',
	variable: '--font-space-grotesk'
})

export const metadata: Metadata = {
	title: 'Gallery App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className={`relative min-h-screen ${space_grotesk.variable}`}>
			<body className=' bg-gradient-to-b from-cyan-100 to-white'>
				<AnimatedBlob className='w-40 absolute -top-16 -left-10 -z-1' stopColor='#FF4D9C' />
				<AnimatedBlob className='w-40 absolute bottom-10 -z-1' stopColor='#6842FF' />
				<main className='font-space'>{children}</main>
			</body>
		</html>
	)
}
