import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthComponent from '@/components/AuthComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className='h-screen bg-gradient-to-b from-cyan-200 to-white'>
				<main className=''>{children}</main>
			</body>
		</html>
	)
}
